Training run name: ethereal-sweep-5 ...
Epoch [1/20] Train Loss: 1.9666, Train Acc: 28.44% | Val Loss: 1.5513, Val Acc: 42.50%
Epoch [2/20] Train Loss: 1.7709, Train Acc: 36.19% | Val Loss: 1.4392, Val Acc: 47.47%
Epoch [3/20] Train Loss: 1.6827, Train Acc: 39.84% | Val Loss: 1.3903, Val Acc: 49.70%
Epoch [4/20] Train Loss: 1.6183, Train Acc: 41.98% | Val Loss: 1.3173, Val Acc: 53.34%
Epoch [5/20] Train Loss: 1.5677, Train Acc: 44.23% | Val Loss: 1.2439, Val Acc: 55.56%
Epoch [6/20] Train Loss: 1.5311, Train Acc: 45.61% | Val Loss: 1.2949, Val Acc: 55.56%
Epoch [7/20] Train Loss: 1.4973, Train Acc: 47.05% | Val Loss: 1.1987, Val Acc: 57.44%
Epoch [8/20] Train Loss: 1.4654, Train Acc: 48.04% | Val Loss: 1.1772, Val Acc: 58.98%
Epoch [9/20] Train Loss: 1.4353, Train Acc: 49.47% | Val Loss: 1.1425, Val Acc: 61.16%
Epoch [10/20] Train Loss: 1.4069, Train Acc: 50.36% | Val Loss: 1.0808, Val Acc: 62.07%
Epoch [11/20] Train Loss: 1.3825, Train Acc: 51.30% | Val Loss: 1.1408, Val Acc: 60.44%
Epoch [12/20] Train Loss: 1.3606, Train Acc: 52.34% | Val Loss: 1.1124, Val Acc: 61.49%
Epoch [13/20] Train Loss: 1.3445, Train Acc: 52.86% | Val Loss: 1.0500, Val Acc: 64.10%
Epoch [14/20] Train Loss: 1.3222, Train Acc: 53.47% | Val Loss: 1.0290, Val Acc: 64.60%
Epoch [15/20] Train Loss: 1.3028, Train Acc: 54.24% | Val Loss: 1.0334, Val Acc: 64.12%
Epoch [16/20] Train Loss: 1.2855, Train Acc: 54.91% | Val Loss: 0.9400, Val Acc: 67.95%
Epoch [17/20] Train Loss: 1.2741, Train Acc: 55.45% | Val Loss: 0.9597, Val Acc: 67.13%
Epoch [18/20] Train Loss: 1.2595, Train Acc: 55.82% | Val Loss: 1.0029, Val Acc: 65.58%
Epoch [19/20] Train Loss: 1.2440, Train Acc: 56.39% | Val Loss: 0.9094, Val Acc: 68.53%
Epoch [20/20] Train Loss: 1.2299, Train Acc: 56.93% | Val Loss: 0.9417, Val Acc: 68.11%
Traceback (most recent call last):
  File "C:\Users\DDA\Downloads\CS6886W-sweep\CS6886W-sweep\trainer.py", line 36, in train
    train_model(model, trainloader, testloader, config, device, wanrun)
  File "C:\Users\DDA\Downloads\CS6886W-sweep\CS6886W-sweep\utils\train.py", line 74, in train_model
    wanrun.save("model.pth")  # Save to WandB run files
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DDA\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DDA\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DDA\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_run.py", line 444, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DDA\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_run.py", line 2129, in save
    return self._save(
           ^^^^^^^^^^^
  File "C:\Users\DDA\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_run.py", line 2188, in _save
    target_path.symlink_to(source_path)
  File "C:\Users\DDA\AppData\Local\Programs\Python\Python311\Lib\pathlib.py", line 1198, in symlink_to
    os.symlink(target, self, target_is_directory)
OSError: [WinError 1314] A required privilege is not held by the client: 'C:\\Users\\DDA\\Downloads\\CS6886W-sweep\\CS6886W-sweep\\model.pth' -> 'C:\\Users\\DDA\\Downloads\\CS6886W-sweep\\CS6886W-sweep\\wandb\\run-20251019_085012-jyexl6y8\\files\\model.pth'
