Training run name: radiant-sweep-4 ...
Epoch [1/20] Train Loss: 2.1591, Train Acc: 19.85% | Val Loss: 1.9294, Val Acc: 27.35%
Epoch [2/20] Train Loss: 2.0662, Train Acc: 24.57% | Val Loss: 1.8440, Val Acc: 32.29%
Epoch [3/20] Train Loss: 2.0206, Train Acc: 26.20% | Val Loss: 1.8024, Val Acc: 33.99%
Epoch [4/20] Train Loss: 1.9905, Train Acc: 27.68% | Val Loss: 1.7763, Val Acc: 33.55%
Epoch [5/20] Train Loss: 1.9630, Train Acc: 28.75% | Val Loss: 1.7246, Val Acc: 35.92%
Epoch [6/20] Train Loss: 1.9489, Train Acc: 29.31% | Val Loss: 1.8338, Val Acc: 29.80%
Epoch [7/20] Train Loss: 1.9293, Train Acc: 30.22% | Val Loss: 1.7457, Val Acc: 33.36%
Epoch [8/20] Train Loss: 1.9080, Train Acc: 31.39% | Val Loss: 1.6480, Val Acc: 38.56%
Epoch [9/20] Train Loss: 1.8989, Train Acc: 31.61% | Val Loss: 1.6351, Val Acc: 40.81%
Epoch [10/20] Train Loss: 1.8787, Train Acc: 32.28% | Val Loss: 1.6231, Val Acc: 42.43%
Epoch [11/20] Train Loss: 1.8628, Train Acc: 33.15% | Val Loss: 1.5840, Val Acc: 43.37%
Epoch [12/20] Train Loss: 1.8510, Train Acc: 33.43% | Val Loss: 1.5836, Val Acc: 41.17%
Epoch [13/20] Train Loss: 1.8379, Train Acc: 33.86% | Val Loss: 1.7934, Val Acc: 34.05%
Epoch [14/20] Train Loss: 1.8216, Train Acc: 34.50% | Val Loss: 1.6972, Val Acc: 40.83%
Epoch [15/20] Train Loss: 1.8128, Train Acc: 35.23% | Val Loss: 1.5994, Val Acc: 44.57%
Epoch [16/20] Train Loss: 1.8058, Train Acc: 35.33% | Val Loss: 1.7245, Val Acc: 40.49%
Epoch [17/20] Train Loss: 1.7910, Train Acc: 36.12% | Val Loss: 1.6957, Val Acc: 41.53%
Epoch [18/20] Train Loss: 1.7767, Train Acc: 36.46% | Val Loss: 1.5709, Val Acc: 44.72%
Epoch [19/20] Train Loss: 1.7669, Train Acc: 37.06% | Val Loss: 1.6729, Val Acc: 39.11%
Epoch [20/20] Train Loss: 1.7470, Train Acc: 37.40% | Val Loss: 1.7088, Val Acc: 40.99%
Traceback (most recent call last):
  File "C:\Users\DDA\Downloads\CS6886W-sweep\CS6886W-sweep\trainer.py", line 36, in train
    train_model(model, trainloader, testloader, config, device, wanrun)
  File "C:\Users\DDA\Downloads\CS6886W-sweep\CS6886W-sweep\utils\train.py", line 74, in train_model
    wanrun.save("model.pth")  # Save to WandB run files
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DDA\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DDA\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DDA\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_run.py", line 444, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DDA\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_run.py", line 2129, in save
    return self._save(
           ^^^^^^^^^^^
  File "C:\Users\DDA\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_run.py", line 2188, in _save
    target_path.symlink_to(source_path)
  File "C:\Users\DDA\AppData\Local\Programs\Python\Python311\Lib\pathlib.py", line 1198, in symlink_to
    os.symlink(target, self, target_is_directory)
OSError: [WinError 1314] A required privilege is not held by the client: 'C:\\Users\\DDA\\Downloads\\CS6886W-sweep\\CS6886W-sweep\\model.pth' -> 'C:\\Users\\DDA\\Downloads\\CS6886W-sweep\\CS6886W-sweep\\wandb\\run-20251019_083421-p8pjdaev\\files\\model.pth'
