Training run name: brisk-sweep-1 ...
Epoch [1/20] Train Loss: 2.1815, Train Acc: 17.04% | Val Loss: 2.1309, Val Acc: 19.73%
Epoch [2/20] Train Loss: 2.0791, Train Acc: 20.47% | Val Loss: 2.0034, Val Acc: 21.23%
Epoch [3/20] Train Loss: 2.0536, Train Acc: 21.34% | Val Loss: 2.1983, Val Acc: 19.16%
Epoch [4/20] Train Loss: 2.0456, Train Acc: 21.49% | Val Loss: 1.8512, Val Acc: 28.22%
Epoch [5/20] Train Loss: 2.0364, Train Acc: 21.78% | Val Loss: 2.0397, Val Acc: 23.01%
Epoch [6/20] Train Loss: 2.0478, Train Acc: 22.13% | Val Loss: 2.0009, Val Acc: 23.89%
Epoch [7/20] Train Loss: 2.0304, Train Acc: 22.41% | Val Loss: 2.0325, Val Acc: 22.64%
Epoch [8/20] Train Loss: 2.0316, Train Acc: 22.56% | Val Loss: 58.8168, Val Acc: 10.68%
Epoch [9/20] Train Loss: 2.0114, Train Acc: 23.34% | Val Loss: 2.1365, Val Acc: 25.08%
Epoch [10/20] Train Loss: 1.9902, Train Acc: 24.59% | Val Loss: 4.5426, Val Acc: 13.46%
Epoch [11/20] Train Loss: 1.9778, Train Acc: 25.27% | Val Loss: 1.8432, Val Acc: 29.22%
Epoch [12/20] Train Loss: 1.9734, Train Acc: 25.23% | Val Loss: 2.0694, Val Acc: 24.34%
Epoch [13/20] Train Loss: 1.9653, Train Acc: 26.06% | Val Loss: 2.1138, Val Acc: 25.47%
Epoch [14/20] Train Loss: 1.9673, Train Acc: 25.96% | Val Loss: 8.4927, Val Acc: 10.04%
Epoch [15/20] Train Loss: 1.9602, Train Acc: 26.07% | Val Loss: 2.5249, Val Acc: 18.18%
Epoch [16/20] Train Loss: 1.9549, Train Acc: 25.92% | Val Loss: 2.1163, Val Acc: 20.22%
Epoch [17/20] Train Loss: 1.9585, Train Acc: 26.21% | Val Loss: 13.5576, Val Acc: 10.00%
Epoch [18/20] Train Loss: 1.9505, Train Acc: 26.22% | Val Loss: 28.1580, Val Acc: 11.89%
Epoch [19/20] Train Loss: 1.9464, Train Acc: 26.50% | Val Loss: 2.1125, Val Acc: 28.19%
Epoch [20/20] Train Loss: 1.9440, Train Acc: 26.44% | Val Loss: 1.8656, Val Acc: 26.86%
Traceback (most recent call last):
  File "C:\Users\DDA\Downloads\CS6886W-sweep\CS6886W-sweep\trainer.py", line 36, in train
    train_model(model, trainloader, testloader, config, device, wanrun)
  File "C:\Users\DDA\Downloads\CS6886W-sweep\CS6886W-sweep\utils\train.py", line 74, in train_model
    wanrun.save("model.pth")  # Save to WandB run files
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DDA\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DDA\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DDA\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_run.py", line 444, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DDA\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_run.py", line 2129, in save
    return self._save(
           ^^^^^^^^^^^
  File "C:\Users\DDA\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_run.py", line 2188, in _save
    target_path.symlink_to(source_path)
  File "C:\Users\DDA\AppData\Local\Programs\Python\Python311\Lib\pathlib.py", line 1198, in symlink_to
    os.symlink(target, self, target_is_directory)
OSError: [WinError 1314] A required privilege is not held by the client: 'C:\\Users\\DDA\\Downloads\\CS6886W-sweep\\CS6886W-sweep\\model.pth' -> 'C:\\Users\\DDA\\Downloads\\CS6886W-sweep\\CS6886W-sweep\\wandb\\run-20251019_073526-7udhan86\\files\\model.pth'
